---

- name: Create a Jenkins instance for each user
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ user.username }}-{{ infra_project_name }}'
    definition: '{{ lookup("template", "jenkins.yml.j2")|from_yaml }}'

- name: Create Jenkins secret for all users  
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "jenkins-secret.yml.j2")|from_yaml }}'